name: Wheels

on: [push]

jobs:
  wheels:
    name: Build ${{ matrix.py }} wheels on ${{ matrix.os }}, ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [auto, aarch64]
        py: [cp36, cp37, cp38, cp39]
        exclude:
          - os: windows-latest
            arch: aarch64
          - os: macos-latest
            arch: aarch64
      fail-fast: false
    env:
      CIBW_BUILD: ${{ matrix.py }}-*
      CIBW_ARCHS_LINUX: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU

      - uses: pypa/cibuildwheel@v2.0.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  sdist:
    name: Build source package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - run: python -m pip install --upgrade pip wheel
      - run: python setup.py sdist

      - run: python -m pip install dist/iminuit-*
      - run: python -m pip install pytest
      - run: python -m pytest

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload:
    needs: [wheels, sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{secrets.pypi_password}}
